-- MySQL Script generated by MySQL Workbench
-- Mon Apr  7 12:20:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema efa0124_ms_denuncia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `efa0124_ms_denuncia` ;

-- -----------------------------------------------------
-- Schema efa0124_ms_denuncia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `efa0124_ms_denuncia` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `efa0124_ms_denuncia` ;

-- -----------------------------------------------------
-- Table `efa0124_ms_denuncia`.`tipo_denuncia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `efa0124_ms_denuncia`.`tipo_denuncia` ;

CREATE TABLE IF NOT EXISTS `efa0124_ms_denuncia`.`tipo_denuncia` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `efa0124_ms_denuncia`.`denuncia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `efa0124_ms_denuncia`.`denuncia` ;

CREATE TABLE IF NOT EXISTS `efa0124_ms_denuncia`.`denuncia` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `denunciador_id` INT NOT NULL,
  `denunciado_id` INT NULL DEFAULT NULL,
  `data` DATETIME NULL DEFAULT NULL,
  `tipo_denuncia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_denuncia_tipo_denuncia_idx` (`tipo_denuncia_id` ASC) VISIBLE,
  CONSTRAINT `fk_denuncia_tipo_denuncia`
    FOREIGN KEY (`tipo_denuncia_id`)
    REFERENCES `efa0124_ms_denuncia`.`tipo_denuncia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
